package controller;

public enum Actions {
	ADD_PRODUCT, ADD_ORDER, ADD_PARTNER, SHOW_DIALOG_ADD_PARTNER, SHOW_DIALOG_ADD_PRODUCT, SHOW_DIALOG_EDIT_PARTNER, EDIT_PARTNER, SHOW_ORDERS, LOAD_PERSISTENCE
}
